#!/bin/bash

set -e
git clone https://gerrit.wikimedia.org/r/mediawiki/core.git mediawiki
cd mediawiki
cat > docker-compose.override.yml <<EOF 
version: '3.7'
services:
  mediawiki:
    user: "\${MW_DOCKER_UID}:\${MW_DOCKER_GID}"
EOF

cat > .env <<EOF
MW_DOCKER_PORT=8080
MW_SCRIPT_PATH=/w
MW_SERVER=http://localhost:8080
MEDIAWIKI_USER=Admin
MEDIAWIKI_PASSWORD=dockerpass
XDEBUG_CONFIG=''
EOF

echo "MW_DOCKER_UID=$(id -u)
MW_DOCKER_GID=$(id -g)" >> .env

export MW_DOCKER_UID=$(id -u)
export MW_DOCKER_GID=$(id -g)

# -d is detached mode - runs containers in the background:
docker-compose up -d

docker-compose exec mediawiki composer update

docker-compose exec mediawiki /bin/bash /docker/install.sh

git clone "https://gerrit.wikimedia.org/r/mediawiki/skins/Vector" skins/Vector
echo "wfLoadSkin( 'Vector' );" >> LocalSettings.php

echo "export MW_INSTALL_DIR="$(pwd)  >> ~/.bashrc
echo "export MW_DOCKER_UID=$(id -u)" >> ~/.bashrc
echo "export MW_DOCKER_GID=$(id -g)" >> ~/.bashrc

git review -s --verbose
