#!/bin/bash

set -e;
git clone https://gerrit.wikimedia.org/r/mediawiki/core.git mediawiki;
cd mediawiki;
cat > docker-compose.override.yml <<EOF 
version: '3.7'
services:
  mediawiki:
    user: "\${MW_DOCKER_UID}:\${MW_DOCKER_GID}"
EOF

export MW_DOCKER_UID=$(id -u);
export MW_DOCKER_GID=$(id -g);

# -d is detached mode - runs containers in the background:
docker-compose up -d;

docker-compose exec mediawiki composer update;

docker-compose exec mediawiki \
bash -c 'php maintenance/install.php \
 --server $MW_SERVER \
 --scriptpath=$MW_SCRIPTPATH \
 --dbtype $MW_DBTYPE \
 --dbpath $MW_DBPATH \
 --lang $MW_LANG \
 --pass $MW_PASS \
 $MW_SITENAME $MW_USER';

git clone "https://gerrit.wikimedia.org/r/mediawiki/skins/Vector" skins/Vector;
echo "wfLoadSkin( 'Vector' );" >> LocalSettings.php;

echo "export MW_INSTALL_DIR="$(pwd)  >> ~/.bashrc;
echo "export MW_DOCKER_UID=$(id -u)" >> ~/.bashrc;
echo "export MW_DOCKER_GID=$(id -g)" >> ~/.bashrc;

git review -s --verbose