#!/bin/bash

mw () {
	if [[ "$@" == "" ]]; then
		cd $MW_INSTALL_DIR
	elif [[ "$@" == "script" ]]; then
		# cause I'm tired of typing cd $MW_SCRIPTS_DIR
		cd $MW_SCRIPTS_DIR
	else
		$MW_SCRIPTS_DIR/"$@"
	fi
}

complete -W "install reinstall start stop bash get config git-update update version script help" mw
